SPECIALISTS = [
    {
        "id": "triage",
        "name": "Alex Chen",
        "title": "Triage Nurse",
        "emoji": "🏥",
        "color": "#ef4444",
        "focus": "severity assessment and acuity triage",
        "initials": "AC",
    },
    {
        "id": "internal",
        "name": "Dr. Sarah Okafor",
        "title": "Internal Medicine",
        "emoji": "🩺",
        "color": "#3b82f6",
        "focus": "general presentation, systemic disease, undifferentiated illness",
        "initials": "SO",
    },
    {
        "id": "cardio",
        "name": "Dr. Marcus Webb",
        "title": "Cardiologist",
        "emoji": "❤️",
        "color": "#dc2626",
        "focus": "cardiac causes, arrhythmia, structural heart disease, vascular",
        "initials": "MW",
    },
    {
        "id": "neuro",
        "name": "Dr. Priya Kapoor",
        "title": "Neurologist",
        "emoji": "🧠",
        "color": "#8b5cf6",
        "focus": "neurological differential, CNS/PNS disease, movement disorders",
        "initials": "PK",
    },
    {
        "id": "id",
        "name": "Dr. James Nkosi",
        "title": "Infectious Disease",
        "emoji": "🦠",
        "color": "#10b981",
        "focus": "infectious etiology, tropical medicine, immunocompromised hosts",
        "initials": "JN",
    },
    {
        "id": "rheum",
        "name": "Dr. Elena Vasquez",
        "title": "Rheumatologist",
        "emoji": "🦴",
        "color": "#f59e0b",
        "focus": "autoimmune disease, connective tissue disorders, inflammatory arthritis",
        "initials": "EV",
    },
    {
        "id": "endo",
        "name": "Dr. David Park",
        "title": "Endocrinologist",
        "emoji": "⚗️",
        "color": "#ec4899",
        "focus": "metabolic and hormonal causes, thyroid, adrenal, pituitary",
        "initials": "DP",
    },
    {
        "id": "onco",
        "name": "Dr. Aisha Brennan",
        "title": "Oncologist",
        "emoji": "🔬",
        "color": "#6366f1",
        "focus": "malignancy workup, paraneoplastic syndromes, cancer mimics",
        "initials": "AB",
    },
    {
        "id": "pulm",
        "name": "Dr. Thomas Reyes",
        "title": "Pulmonologist",
        "emoji": "🫁",
        "color": "#14b8a6",
        "focus": "respiratory causes, pulmonary disease, sleep disorders",
        "initials": "TR",
    },
    {
        "id": "gastro",
        "name": "Dr. Leila Ahmad",
        "title": "Gastroenterologist",
        "emoji": "🩻",
        "color": "#f97316",
        "focus": "GI causes, hepatic disease, malabsorption, inflammatory bowel",
        "initials": "LA",
    },
    {
        "id": "heme",
        "name": "Dr. Samuel Johansson",
        "title": "Hematologist",
        "emoji": "🩸",
        "color": "#b91c1c",
        "focus": "blood disorders, anemia workup, coagulopathy, lymphoma",
        "initials": "SJ",
    },
    {
        "id": "nephro",
        "name": "Dr. Fatima Al-Rashid",
        "title": "Nephrologist",
        "emoji": "🫘",
        "color": "#0891b2",
        "focus": "renal causes, electrolyte disorders, glomerular disease",
        "initials": "FR",
    },
    {
        "id": "radiology",
        "name": "Dr. Chen Wei",
        "title": "Radiologist",
        "emoji": "🖥️",
        "color": "#7c3aed",
        "focus": "imaging interpretation, radiological findings, pattern recognition",
        "initials": "CW",
    },
    {
        "id": "path",
        "name": "Dr. Yuki Tanaka",
        "title": "Pathologist",
        "emoji": "🔭",
        "color": "#92400e",
        "focus": "lab and pathology analysis, histology, biomarkers",
        "initials": "YT",
    },
    {
        "id": "derm",
        "name": "Dr. Kofi Mensah",
        "title": "Dermatologist",
        "emoji": "🧬",
        "color": "#be185d",
        "focus": "cutaneous findings, skin manifestations of systemic disease",
        "initials": "KM",
    },
    {
        "id": "psych",
        "name": "Dr. Rachel Goldstein",
        "title": "Psychiatrist",
        "emoji": "🧩",
        "color": "#4338ca",
        "focus": "psychiatric differential, organic causes of psychiatric symptoms",
        "initials": "RG",
    },
    {
        "id": "immuno",
        "name": "Dr. Marco Di Luca",
        "title": "Immunologist",
        "emoji": "🛡️",
        "color": "#047857",
        "focus": "immune disorders, primary immunodeficiency, hypersensitivity",
        "initials": "ML",
    },
    {
        "id": "genetics",
        "name": "Dr. Amara Diallo",
        "title": "Geneticist",
        "emoji": "🧪",
        "color": "#9333ea",
        "focus": "hereditary conditions, metabolic genetics, chromosomal disorders",
        "initials": "AD",
    },
    {
        "id": "er",
        "name": "Dr. Lena Sorensen",
        "title": "Emergency Medicine",
        "emoji": "🚨",
        "color": "#dc2626",
        "focus": "acute presentations, time-critical diagnoses, life threats",
        "initials": "LS",
    },
    {
        "id": "critic",
        "name": "Dr. House",
        "title": "Senior Diagnostician",
        "emoji": "🎩",
        "color": "#d97706",
        "focus": "challenge all reasoning, find the diagnosis everyone else missed",
        "initials": "DH",
    },
]
